# -*- coding: utf-8 -*-
"""dashboard_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o60fg4EF7vHvr07RIIzAoTzA8Lm8ji23
"""

# dashboard_app.py - Consolidated Code with Real Spotify API and RandomForest

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px # Import plotly.express
from datetime import datetime, timedelta
# Libraries for Data Acquisition and Modeling
from meteostat import Point, Daily
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from spotipy.oauth2 import SpotifyClientCredentials

# --- 0. CONFIGURATION AND SECRETS ---

# Create .streamlit directory if it doesn't exist
#import os
#if not os.path.exists('.streamlit'):
 #   os.makedirs('.streamlit')

# Write secrets.toml file if it doesn't exist or is empty
#secrets_path = '.streamlit/secrets.toml'
"""if not os.path.exists(secrets_path) or os.stat(secrets_path).st_size == 0:
    with open(secrets_path, 'w') as f:
        f.write('spotify_client_id = "YOUR_SPOTIFY_CLIENT_ID"\n')
        f.write('spotify_secret = "YOUR_SPOTIFY_SECRET"\n')
    st.warning("Please replace 'YOUR_SPOTIFY_CLIENT_ID' and 'YOUR_SPOTIFY_SECRET' in .streamlit/secrets.toml with your actual Spotify API credentials.")
    st.stop()"""

# Streamlit will automatically load these secrets from .streamlit/secrets.toml
try:
    SPOTIFY_CLIENT_ID = st.secrets["spotify_client"]
    SPOTIFY_SECRET = st.secrets["spotify_secret"]
except KeyError:
    st.error("Spotify credentials not found. Ensure .streamlit/secrets.toml is configured with 'spotify_client' and 'spotify_secret'.")
    st.stop()


# Location and Time (Used for Weather)
LOCATION_NAME = "New York City"
LAT, LON, ELEVATION = 40.71, -74.01, 10
END_DATE = datetime.now().date()
START_DATE = END_DATE - timedelta(days=90) # Last 90 days for training window

# Spotify Chart/Playlist URI (Using Global Top 50 as an example source)
CHART_PLAYLIST_URI = 'spotify:playlist:37i9dQZEVXbMDoHDwVN2tF'

# Features used by the Random Forest Model
FEATURES = [
    'popularity_lag_1', 'energy', 'valence', 'tempo', 'danceability',
    'tavg', 'prcp', 'daylight_hours',
    'month_sin', 'month_cos',
    'is_weekend'
]
NUM_TRACKS = 50 # Assuming 50 tracks from the top chart

# --- 1. DATA ACQUISITION & INTEGRATION (STEPS 1-3) ---

@st.cache_data(show_spinner="1. Fetching Real Spotify and Historical Weather Data...")
def get_integrated_data():
    """Fetches real-time Spotify audio features and historical weather data."""

    # 1. Initialize Spotify Client
    sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(
        client_id=SPOTIFY_CLIENT_ID,
        client_secret=SPOTIFY_SECRET
    ))

    # 2. Fetch Track Features from a Chart/Playlist (Fetches CURRENT state)
    st.info(f"Fetching audio features for tracks in playlist: {CHART_PLAYLIST_URI}")
    results = sp.playlist_tracks(CHART_PLAYLIST_URI)
    track_ids = [item['track']['id'] for item in results['items'] if item['track']]

    audio_features_list = sp.audio_features(track_ids[:NUM_TRACKS]) # Limit to top tracks

    music_data = []
    for track_feature in audio_features_list:
        if track_feature:
             music_data.append({
                'track_id': track_feature['id'],
                'energy': track_feature['energy'],
                'valence': track_feature['valence'],
                'tempo': track_feature['tempo'],
                'danceability': track_feature['danceability'],
                # Placeholder popularity for modeling historical trend:
                'popularity': 75
             })

    music_features_df = pd.DataFrame(music_data)

    # 3. Fetch Weather Data (Historical)
    st.info(f"Fetching historical weather data for {LOCATION_NAME}...")
    location = Point(LAT, LON, ELEVATION)
    weather_data = Daily(location, START_DATE, datetime.now())
    weather_df = weather_data.fetch().reset_index().rename(columns={'time': 'date'})
    weather_df = weather_df[['date', 'tavg', 'prcp', 'tsun']].copy()
    weather_df['daylight_hours'] = weather_df['tsun'].fillna(0) / 60
    weather_df.drop(columns=['tsun'], inplace=True)
    weather_df.dropna(subset=['tavg'], inplace=True)

    # 4. Integrate Data (Cross-Join: Every track feature with every historical weather date)
    music_features_df['key'] = 0
    weather_df['key'] = 0

    master_df = pd.merge(music_features_df, weather_df, on='key').drop('key', axis=1)

    # --- Feature Engineering ---
    master_df['date'] = master_df['date'].dt.date
    master_df['month'] = master_df['date'].apply(lambda x: x.month)
    master_df['is_weekend'] = pd.to_datetime(master_df['date']).dt.weekday.apply(lambda x: 1 if x >= 5 else 0)

    # Cyclical Features

# [Image of sine cosine wave plot]

    master_df['month_sin'] = np.sin(2 * np.pi * master_df['month'] / 12)
    master_df['month_cos'] = np.cos(2 * np.pi * master_df['month'] / 12)

    # Lagged Popularity (Simulated historical trend for modeling)
    master_df = master_df.sort_values(by=['track_id', 'date']).reset_index(drop=True)
    master_df['popularity_lag_1'] = master_df.groupby('track_id')['popularity'].transform(lambda x: x.ewm(span=7).mean().shift(1))

    master_df.dropna(subset=['popularity_lag_1'], inplace=True)

    return master_df

# --- 2. MODEL TRAINING (STEP 4) ---

@st.cache_resource(show_spinner="2. Training Random Forest Regressor...")
def train_model(data_df):
    """Trains the Random Forest Regressor model and extracts validation data."""

    X = data_df[FEATURES]
    y = data_df['popularity']

    # Chronological Split (80% Train, 20% Test)
    split_point = int(len(X) * 0.8)
    X_train, X_test = X[:split_point], X[split_point:]
    y_train, y_test = y[:split_point], y[split_point:]

    # Train Random Forest Regressor
    model = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1)
    model.fit(X_train, y_train)

    # Predict and Validate
    y_pred = model.predict(X_test)

    validation_df = pd.DataFrame({
        'date': data_df['date'].tail(len(y_test)),
        'actual_popularity': y_test,
        'predicted_popularity': y_pred
    })

    return model, validation_df

# --- 3. FORECASTING (STEP 7) ---

@st.cache_data(show_spinner="3. Generating 30-Day Forecast...")
def generate_forecast(model, data_df, days=30):
    """Generates a forward 30-day forecast."""

    last_date = data_df['date'].max()
    future_dates = pd.to_datetime([last_date + timedelta(days=d) for d in range(1, days + 1)]).date
    forecast_df = pd.DataFrame({'date': future_dates})

    # Prepare historical stats for simulating future features
    data_df['month'] = data_df['date'].apply(lambda x: x.month)
    seasonal_stats = data_df.groupby('month')[['tavg', 'prcp', 'daylight_hours']].mean().mean()

    # Simulate Future Features
    forecast_df['tavg'] = seasonal_stats['tavg'] + np.random.normal(0, 3, days)
    forecast_df['prcp'] = seasonal_stats['prcp'] * np.random.uniform(0.5, 1.5, days)
    forecast_df['daylight_hours'] = seasonal_stats['daylight_hours'] + np.random.normal(0, 1, days)

    # Feature Engineering for Forecast
    forecast_df['month'] = pd.to_datetime(forecast_df['date']).dt.month
    forecast_df['is_weekend'] = pd.to_datetime(forecast_df['date']).dt.weekday.apply(lambda x: 1 if x >= 5 else 0)
    forecast_df['month_sin'] = np.sin(2 * np.pi * forecast_df['month'] / 12)
    forecast_df['month_cos'] = np.cos(2 * np.pi * forecast_df['month'] / 12)

    # Lagged Popularity (Last known value)
    last_lag_value = data_df['popularity_lag_1'].mean()
    forecast_df['popularity_lag_1'] = last_lag_value

    # Song Attributes (Average values)
    for feature in ['energy', 'valence', 'tempo', 'danceability']:
        forecast_df[feature] = data_df[feature].mean()

    # Make Forecast
    X_forecast = forecast_df[FEATURES]
    forecast_predictions = model.predict(X_forecast)

    forecast_df['predicted_popularity'] = np.round(forecast_predictions).astype(int)
    return forecast_df[['date', 'predicted_popularity', 'tavg', 'daylight_hours', 'month']]


# --- 4. STREAMLIT APPLICATION LAYOUT AND VISUALIZATION (STEP 8) ---

# Execution Order: Load Data -> Train Model -> Generate Forecast
master_df = get_integrated_data()
model, validation_df = train_model(master_df)
forecast_df = generate_forecast(model, master_df)

# Calculate final R2 metric for display
r2 = r2_score(validation_df['actual_popularity'], validation_df['predicted_popularity'])

# --- Dashboard Header and Layout ---
st.set_page_config(layout="wide", page_title="Song Trend Forecasting 🎶")
st.title("🎶 Seasonal Song Trend Forecasting Dashboard (Real Data)")
st.markdown(f"### Location: {LOCATION_NAME} | Training Window: {START_DATE} to {END_DATE}")

# Sidebar Metrics
st.sidebar.header("Model Performance Metrics")
st.sidebar.metric(label="R-squared (R²)", value=f"{r2:.4f}")
st.sidebar.markdown("**Note:** The model predicts the *potential* popularity trend based on audio features and weather correlation.")

# ----------------------------------------------------
## 1. Historical Model Validation
# ----------------------------------------------------
st.header("1. Historical Model Validation (Actual vs. Predicted)")

fig_validation = go.Figure()
fig_validation.add_trace(go.Scatter(x=validation_df['date'], y=validation_df['actual_popularity'],
                                    mode='lines', name='Actual Popularity', line=dict(color='red', width=3)))
fig_validation.add_trace(go.Scatter(x=validation_df['date'], y=validation_df['predicted_popularity'],
                                    mode='lines', name='Predicted Popularity', line=dict(color='blue', dash='dot', width=2)))

fig_validation.update_layout(xaxis_title='Date', yaxis_title='Popularity Score', hovermode="x unified", height=400)
st.plotly_chart(fig_validation, use_container_width=True)

# ----------------------------------------------------
## 2. 30-Day Forward Trend Forecast
# ----------------------------------------------------
st.header("2. 30-Day Forward Trend Forecast")

col1, col2 = st.columns(2)

with col1:
    # Chart A: Predicted Popularity
    fig_forecast_pop = go.Figure()
    fig_forecast_pop.add_trace(go.Scatter(x=forecast_df['date'], y=forecast_df['predicted_popularity'],
                                           mode='lines+markers', name='Predicted Popularity', line=dict(color='red', width=3)))
    fig_forecast_pop.update_layout(title='Predicted Song Popularity', xaxis_title='Date', yaxis_title='Popularity Score', hovermode="x unified", height=400)
    st.plotly_chart(fig_forecast_pop, use_container_width=True)

with col2:
    # Chart B: Forecasted Weather Drivers
    fig_weather = go.Figure()
    fig_weather.add_trace(go.Scatter(x=forecast_df['date'], y=forecast_df['tavg'],
                                     mode='lines', name='Avg. Temp (°C)', yaxis='y1', line=dict(color='orange', width=2)))

    fig_weather.add_trace(go.Scatter(x=forecast_df['date'], y=forecast_df['daylight_hours'],
                                     mode='lines', name='Daylight Hours', yaxis='y2', line=dict(color='skyblue', dash='dot', width=2)))

    fig_weather.update_layout(title='Forecasted Weather Drivers', xaxis_title='Date',
        yaxis=dict(title='Avg. Temp (°C)', color='orange'),
        yaxis2=dict(title='Daylight Hours', overlaying='y', side='right', color='skyblue'),
        hovermode="x unified", height=400)
    st.plotly_chart(fig_weather, use_container_width=True)

# ----------------------------------------------------
## 3. Seasonal Trends of Key Features (Visualization of correlation)
# ----------------------------------------------------
st.header("3. Seasonal Trends of Key Features")
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

seasonal_df = master_df.groupby(master_df['date'].apply(lambda x: x.month))[['valence', 'energy', 'tavg']].mean().reset_index()
seasonal_df['Month'] = seasonal_df['date'].apply(lambda x: months[x - 1])

# Plot Valence (Mood) and Energy vs. Month
fig_seasonal = px.line(seasonal_df, x='Month', y=['valence', 'energy'],
                       title='Average Song Valence (Mood) and Energy by Month',
                       labels={'value': 'Score (0-1)', 'Month': 'Month'},
                       color_discrete_map={'valence': 'green', 'energy': 'blue'})

# Add Temperature as a secondary axis for seasonal context
fig_seasonal.add_trace(go.Scatter(x=seasonal_df['Month'], y=seasonal_df['tavg'],
                                  name='Avg. Temp (°C)', yaxis='y2', mode='lines',
                                  line=dict(color='red', dash='dash')))

fig_seasonal.update_layout(
    yaxis=dict(title='Score (0-1)'),
    yaxis2=dict(title='Avg. Temp (°C)', overlaying='y', side='right', showgrid=False),
    hovermode="x unified"
)
st.plotly_chart(fig_seasonal, use_container_width=True)
